### ISSUE TITLE
Mac Mini Theta Edge Node can't connect

### ISSUE THREAD

**Issue by theta-netizen** [thetatoken/guardian-mainnet-guide#120]
Hi,

I'm on Mac OS Catalina 10.15.7, Theta Edge Node - 2.3.94, Mac Mini 2012 - i5 Quad Core, 16GB RAM.

Elite Edge Node Testnet - Just shows connecting to Testnet - does not connect - left it on overnight.

Watch window shows nothing - keeps loading...

Broadcast shows "Updating Stream Info" - keeps loading..

Edge Compute - there is no job - 0.00% completed.

Firewall is Off. No Antivirus.

Terminal Window shows these errors while launching -
[info] [ThetaEdgeLauncher] time="2021-06-08T18:31:00+05:30" level=error msg="Failed to execute command: /Applications/Theta Edge Node.app/Contents/Resources/bin/anycast start --config=/Users/username/Library/Application Support/Theta Edge Node/ThetaEdgeNode/edgecast, err: exit status 2" prefix=launcher

[info] [ThetaEdgeCompute:FoldingAtHome] 13:01:19:WARNING:WU00:FS00:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
13:01:19:ERROR:WU00:FS00:Exception: Could not get an assignment

And the following warning message which keeps looping -
[info] [ThetaEdgeLauncher] time="2021-06-08T11:47:38+05:30" level=warning msg="client.Call res: <nil>, error: Post \"http://127.0.0.1:7935/rpc\": dial tcp 127.0.0.1:7935: connect: connection refused" prefix=launcher

My 2 Windows laptops on the same network connect fine. 

Can anyone help with this? Thank you.

**Comment by Leozz09** [comment]
Here I am have the same issue on Windows 10 pro. 
Anyone can help? Many thanks.

**Comment by Adam-Jack12** [comment]
@Leozz09 What version of EN are you running on ?

**Comment by alex-bochkov** [comment]
@Adam-Jack12 is a scammer

**Comment by Adam-Jack12** [comment]
@alekseybochkov Are you crazy ? What’s with the wrong allegations

**Comment by alex-bochkov** [comment]
Go ahead, invite me into your Telegram group.
You have my full attention going forward 😘

**Comment by Adam-Jack12** [comment]
What telegram group ?
Are you silly ?

**Comment by Leozz09** [comment]
> @Leozz09 What version of EN are you running on ?

how can I know which version running?

**Comment by mlowicki** [comment]
I've the same issue with Theta Edge Node Beta 3.0.6 on OSX. It worked for months without issues but now it stopped.

**Comment by AdamssSmith** [comment]
@mlowicki Hello Mate, Sorry to hear about your issue, you can join the telegram group and contact the Theta Network Support on Telegram via the weblink https://t.me/thetanetworking
They'll be happy to resolve your issue. Cheers.

**Comment by alex-bochkov** [comment]
Ignore this scammer
![image](https://user-images.githubusercontent.com/13791336/127243590-356df1c2-1462-4db3-bb57-39e6135fb282.png)

**Comment by mlowicki** [comment]
```
[2021-07-28 02:17:58.857] [info] [ThetaEdgeLauncher] time="2021-07-28T02:17:58+02:00" level=warning msg="client.Call res: <nil>, error: Post \"http://127.0.0.1:7935/rpc\": dial tcp 127.0.0.1:7935: connect: connection refused" prefix=launcher

[2021-07-28 02:18:17.506] [info] Checking for update
[2021-07-28 02:18:17.769] [info] [ThetaEdgeLauncher] started
[2021-07-28 02:18:17.852] [info] [ThetaEdgeLauncher] Using config file: /Users/mlowicki/Library/Application Support/Theta Edge Node/ThetaEdgeNode/edgelauncher/config.yaml

[2021-07-28 02:18:17.910] [info] [ThetaEdgeLauncher] time="2021-07-28T02:18:17+02:00" level=info msg="Stopping the edgecore process..." prefix=launcher

[2021-07-28 02:18:17.996] [info] [ThetaEdgeLauncher] time="2021-07-28T02:18:17+02:00" level=info msg="Stopping the anycast process..." prefix=launcher
time="2021-07-28T02:18:17+02:00" level=info msg="anycast started." prefix=launcher
time="2021-07-28T02:18:17+02:00" level=info msg="Setup wallet..." prefix=launcher

[2021-07-28 02:18:18.344] [info] [ThetaEdgeLauncher] SIGILL: illegal instruction
PC=0x4d4630a m=0 sigcode=1
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:

[2021-07-28 02:18:18.344] [info] [ThetaEdgeLauncher] runtime.cgocall(0x4cd00f0, 0xc00063fd88, 0x5063cd7)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc00063fd58 sp=0xc00063fd20 pc=0x40077bb

[2021-07-28 02:18:18.345] [info] [ThetaEdgeLauncher] github.com/herumi/bls-eth-go-binary/bls._Cfunc_blsInit(0xf600000005, 0x0)
	_cgo_gotypes.go:415 +0x4d fp=0xc00063fd88 sp=0xc00063fd58 pc=0x4a28a4d
github.com/herumi/bls-eth-go-binary/bls.Init(0x5, 0x70a4855d04d8fa7b, 0x6)
	/Users/jieyilong/Theta/go/pkg/mod/github.com/weiribao/bls-eth-go-binary@v0.0.0-20201111191332-dd9cfd3ea8f0/bls/bls.go:54 +0x40 fp=0xc00063fde0 sp=0xc00063fd88 pc=0x4a2ad70

[2021-07-28 02:18:18.346] [info] [ThetaEdgeLauncher] github.com/thetatoken/theta/crypto/bls.init.0()
	/Users/jieyilong/Theta/go/src/github.com/thetatoken/theta/crypto/bls/bls.go:13 +0x2a fp=0xc00063fe08 sp=0xc00063fde0 pc=0x4a2ffaa
runtime.doInit(0x5dfde60)
	/usr/local/go/src/runtime/proc.go:5414 +0x8a fp=0xc00063fe38 sp=0xc00063fe08 pc=0x404784a
runtime.doInit(0x5e0a980)
	/usr/local/go/src/runtime/proc.go:5409 +0x57 fp=0xc00063fe68 sp=0xc00063fe38 pc=0x4047817
runtime.doInit(0x5e04620)
	/usr/local/go/src/runtime/proc.go:5409 +0x57 fp=0xc00063fe98 sp=0xc00063fe68 pc=0x4047817
runtime.doInit(0x5e0c2a0)
	/usr/local/go/src/runtime/proc.go:5409 +0x57 fp=0xc00063fec8 sp=0xc00063fe98 pc=0x4047817
runtime.doInit(0x5e0dfa0)
	/usr/local/go/src/runtime/proc.go:5409 +0x57 fp=0xc00063fef8 sp=0xc00063fec8 pc=0x4047817
runtime.doInit(0x5e0cde0)
	/usr/local/go/src/runtime/proc.go:5409 +0x57 fp=0xc00063ff28 sp=0xc00063fef8 pc=0x4047817
runtime.doInit(0x5e0a880)
	/usr/local/go/src/runtime/proc.go:5409 +0x57 fp=0xc00063ff58 sp=0xc00063ff28 pc=0x4047817
runtime.doInit(0x5df8100)
	/usr/local/go/src/runtime/proc.go:5409 +0x57 fp=0xc00063ff88 sp=0xc00063ff58 pc=0x4047817
runtime.main()
	/usr/local/go/src/runtime/proc.go:190 +0x1ce fp=0xc00063ffe0 sp=0xc00063ff88 pc=0x403ac2e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00063ffe8 sp=0xc00063ffe0 pc=0x406b601

goroutine 19 [select]:

[2021-07-28 02:18:18.347] [info] [ThetaEdgeLauncher] github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc0000a7bf0)
	/Users/jieyilong/Theta/go/pkg/mod/github.com/ipfs/go-log@v1.0.4/writer/writer.go:71 +0x128
created by github.com/ipfs/go-log/writer.NewMirrorWriter
	/Users/jieyilong/Theta/go/pkg/mod/github.com/ipfs/go-log@v1.0.4/writer/writer.go:36 +0xb9

goroutine 34 [chan receive]:

[2021-07-28 02:18:18.347] [info] [ThetaEdgeLauncher] github.com/golang/glog.(*loggingT).flushDaemon(0x5f5b740)
	/Users/jieyilong/Theta/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	/Users/jieyilong/Theta/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x26f

goroutine 35 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000284100)
	/Users/jieyilong/Theta/go/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:276 +0x100
created by go.opencensus.io/stats/view.init.0
	/Users/jieyilong/Theta/go/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:34 +0x68

rax    0x1641c197c797d174
rbx    0x0
rcx    0xe9be3e6838682e8c
rdx    0x27c40feacb23745c
rdi    0x6fe3fd0
rsi    0x7ffeefbff4d0
rbp    0x0
rsp    0x7ffeefbff310
r8     0x1
r9     0x0
r10    0x0
r11    0x5f4dce8
r12    0x0
r13    0x1ce44bcc87acea26
r14    0x0
r15    0x4d45b50
rip    0x4d4630a
rflags 0x10246
cs     0x2b
fs     0x0
gs     0x0

[2021-07-28 02:18:18.350] [info] [ThetaEdgeLauncher] time="2021-07-28T02:18:18+02:00" level=error msg="Failed to execute command: /Applications/Theta Edge Node.app/Contents/Resources/bin/anycast start --config=/Users/mlowicki/Library/Application Support/Theta Edge Node/ThetaEdgeNode/edgecast, err: exit status 2" prefix=launcher

[2021-07-28 02:18:18.769] [info] Update for version 3.0.6 is not available (latest version: 3.0.6, downgrade is disallowed).
[2021-07-28 02:18:18.997] [info] [ThetaEdgeLauncher] time="2021-07-28T02:18:18+02:00" level=warning msg="client.Call res: <nil>, error: Post \"http://127.0.0.1:7935/rpc\": dial tcp 127.0.0.1:7935: connect: connection refused" prefix=launcher

[2021-07-28 02:18:19.998] [info] [ThetaEdgeLauncher] time="2021-07-28T02:18:19+02:00" level=warning msg="client.Call res: <nil>, error: Post \"http://127.0.0.1:7935/rpc\": dial tcp 127.0.0.1:7935: connect: connection refused" prefix=launcher

[2021-07-28 02:18:21.002] [info] [ThetaEdgeLauncher] time="2021-07-28T02:18:21+02:00" level=warning msg="client.Call res: <nil>, error: Post \"http://127.0.0.1:7935/rpc\": dial tcp 127.0.0.1:7935: connect: connection refused" prefix=launcher

[2021-07-28 02:18:22.005] [info] [ThetaEdgeLauncher] time="2021-07-28T02:18:22+02:00" level=warning msg="client.Call res: <nil>, error: Post \"http://127.0.0.1:7935/rpc\": dial tcp 127.0.0.1:7935: connect: connection refused" prefix=launcher
```
