### ISSUE TITLE
SIGSEGV  panic in routine Trie

### ISSUE THREAD

**Issue by the-quantum-rabbit** [thetatoken/guardian-mainnet-guide#62]
Could not find a core:  Is there a patch?

Node running on 
mike@beta-1:~/theta_mainnet/bin$ uname -a
Linux beta-1 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

LOG entries and stack follow:

LOG:- at time of error
09:04:34.230009 version@stat F·[0 40 946 7464 28135] S·62GiB[0B 8MiB 983MiB 9GiB 51GiB] Sc·[0.00 0.09 0.98 1.00 0.53]
09:04:34.238763 table@compaction committed F-1 S-9KiB Ke·0 D·22 T·266.453358ms
09:04:34.239024 table@remove removed @44734089
09:04:34.241185 table@remove removed @44726931
09:04:34.241346 table@remove removed @44717833
09:04:34.241486 table@remove removed @44717834
09:04:34.241627 table@remove removed @44717835
09:04:34.241880 table@remove removed @44717836
09:04:34.242042 table@remove removed @44717837
09:04:34.242201 table@remove removed @44717838
09:04:34.242358 table@remove removed @44717839
09:04:34.242514 table@remove removed @44717840
09:04:34.242597 table@remove removed @44717841
09:04:34.242791 table@remove removed @44717911
09:04:34.269355 table@compaction L2·1 -> L3·11 S·20MiB Q·398217829
09:04:34.301552 table@build created L3@44738557 N·6441 S·2MiB "\xf1d\b..3:\xbd,v312927474":"\xf1fX../\x96\x02,v330495071"
09:04:34.325070 table@build created L3@44738558 N·6341 S·2MiB "\xf1fX..@\x14;,v115681575":"\xf1h\x9c..\xdc\x05_,v356482471"
09:04:34.346975 table@build created L3@44738559 N·6336 S·2MiB "\xf1h\x9c..plw,v250416537":"\xf1j\xe5..\xbb2\x92,v242065969"
09:04:34.370884 table@build created L3@44738560 N·5760 S·2MiB "\xf1j\xe5..\xca'\xeb,v67831262":"\xf1l\xfa..t;\xcc,v142340389"
09:04:34.397232 table@build created L3@44738561 N·6139 S·2MiB "\xf1l\xfb..\\\x1d\xde,v70526785":"\xf1o...4w\xf3,v353745142"

Consol messages

[2021-03-02 09:04:02]  INFO [ledger] Block reward for staker e9bf36ec9b67fc94a95619718e7a8b8fd46444d5 : 0 ThetaWei, 258866274378534878 TFuelWei
[2021-03-02 09:04:02]  INFO [ledger] Block reward for staker f2c2f4e33c3d95ee992470976c7c8de5ff37423d : 0 ThetaWei, 190702206161655559 TFuelWei
[2021-03-02 09:04:02]  INFO [ledger] Block reward for staker c7ab5146edace4b52150b81d6fdebe5f886402ff : 0 ThetaWei, 60529241929133690 TFuelWei
[2021-03-02 09:04:03]  INFO [request] Sync progress current chain tip=0x391c9b54c0d4dee177e0aaf7238182e13b006c883c229411173c0cd39387f8ea orphan blocks=0 pending block hashes=1214
[2021-03-02 09:04:06]  INFO [request] Sync progress current chain tip=0x391c9b54c0d4dee177e0aaf7238182e13b006c883c229411173c0cd39387f8ea orphan blocks=0 pending block hashes=1214
[2021-03-02 09:04:09]  INFO [ledger] Commit to data store, height: 9393801, rootHash: 0x7c1461d6b29225259b7dbb1fbdbd416fd16d8eee7838bbc38f5db1bd1074e0d4
[2021-03-02 09:04:10]  INFO [request] Sync progress current chain tip=0x391c9b54c0d4dee177e0aaf7238182e13b006c883c229411173c0cd39387f8ea orphan blocks=0 pending block hashes=1214
[2021-03-02 09:04:11]  INFO [mempool] Insert tx, tx.hash: 0xeb8c9d3eaac3455854677030ef1f42613aae2d87e63af5cf14e876a8920862c0
[2021-03-02 09:04:11]  INFO [consensus] Finalizing block block.Hash=0x391c9b54c0d4dee177e0aaf7238182e13b006c883c229411173c0cd39387f8ea block.Height=9393800
[2021-03-02 09:04:11]  INFO [consensus] Notified finalized block, height=9393800
[2021-03-02 09:04:11]  INFO [rpc] Processing finalized block, height=9393800
[2021-03-02 09:04:11]  INFO [rpc] Done processing finalized block, height=9393800
[2021-03-02 09:04:12]  INFO [ledger] Commit to data store, height: 9393802, rootHash: 0x381c21eaf50b4fdcadefdf6d05221e59793ebdeb27793da4e167ca72e67c54c0
[2021-03-02 09:04:14]  INFO [request] Sync progress current chain tip=0xfc663d583fd65e6380a2b01a0948b6e56469662d708578b85a6f895385ee71ed orphan blocks=0 pending block hashes=1214
[2021-03-02 09:04:14]  WARN [ledger] validateSourceAdvanced failed on 0x4325188DF8EADDAb602274CD66c13e198F46B5c3: Result{code:100003, message:Insufficient fund: balance is 0 ThetaWei, 0 TFuelWei, tried to send 0 ThetaWei, 5000000000000000000 TFuelWei}
[2021-03-02 09:04:14]  INFO [consensus] Finalizing block block.Hash=0xfc663d583fd65e6380a2b01a0948b6e56469662d708578b85a6f895385ee71ed block.Height=9393801
[2021-03-02 09:04:15] DEBUG [guardian] Starting new block block=0xfc663d583fd65e6380a2b01a0948b6e56469662d708578b85a6f895385ee71ed gcp=0xa97d7dfb38643c06bf41e9bf69fbda3fec6b1a5fe77caeae6c23545457a4a1b1 signerIndex=1577
[2021-03-02 09:04:15]  INFO [consensus] Notified finalized block, height=9393801
[2021-03-02 09:04:15]  INFO [rpc] Processing finalized block, height=9393801
[2021-03-02 09:04:15]  INFO [rpc] Done processing finalized block, height=9393801
[2021-03-02 09:04:15]  INFO [ledger] Commit to data store, height: 9393803, rootHash: 0xb45dbb1a1740be61da5b0736c420acf7d8d8b0bd5bf1b0ab0a8c8baf4955ee2a
[2021-03-02 09:04:17]  INFO [consensus] Finalizing block block.Hash=0x33bbee7bb632410a933a6bf761a4c6a29123bd7b06416465807ede6a1dc67cdc block.Height=9393802
[2021-03-02 09:04:17]  INFO [consensus] Notified finalized block, height=9393802
[2021-03-02 09:04:17]  INFO [rpc] Processing finalized block, height=9393802
[2021-03-02 09:04:17]  INFO [rpc] Done processing finalized block, height=9393802
[2021-03-02 09:04:17]  INFO [ledger] Commit to data store, height: 9393804, rootHash: 0xdf06279a171eb734b712bb59e155599c0f33d2d85478a95c8a553c0b849d2269
[2021-03-02 09:04:18]  INFO [request] Sync progress current chain tip=0xa9d9d3fb00c7fe271eb250d011b75f150d482f5c048dd0f66168e8d24a119fe6 orphan blocks=0 pending block hashes=1214
[2021-03-02 09:04:20]  INFO [consensus] Finalizing block block.Hash=0xa9d9d3fb00c7fe271eb250d011b75f150d482f5c048dd0f66168e8d24a119fe6 block.Height=9393803
[2021-03-02 09:04:20]  INFO [consensus] Notified finalized block, height=9393803
[2021-03-02 09:04:20]  INFO [rpc] Processing finalized block, height=9393803
[2021-03-02 09:04:20]  INFO [rpc] Done processing finalized block, height=9393803
[2021-03-02 09:04:20]  INFO [ledger] Commit to data store, height: 9393805, rootHash: 0x9826fccb0515beda3dd664646d65ae7d54106022a575d21eedce4db55d589d63
[2021-03-02 09:04:22]  INFO [request] Sync progress current chain tip=0x8ee57c82e33a7a1fc98050248a309a1e5a377b79e6ef8452e07d7d58fc9611e3 orphan blocks=0 pending block hashes=1214
[2021-03-02 09:04:23]  INFO [consensus] Finalizing block block.Hash=0x8ee57c82e33a7a1fc98050248a309a1e5a377b79e6ef8452e07d7d58fc9611e3 block.Height=9393804
[2021-03-02 09:04:23]  INFO [consensus] Notified finalized block, height=9393804
[2021-03-02 09:04:23]  INFO [rpc] Processing finalized block, height=9393804
[2021-03-02 09:04:23]  INFO [rpc] Done processing finalized block, height=9393804
[2021-03-02 09:04:23]  INFO [ledger] Commit to data store, height: 9393806, rootHash: 0xb1aa8ffe99a1ceed4d37bcbae996293b7e7f85036c7ceb2530c0a2818a1164f8
[2021-03-02 09:04:24]  INFO [p2p] Already has sufficient number of peers, numPeers: 24, sufficientNumPeers: 24
[2021-03-02 09:04:24]  WARN [p2p] Failed to perform NAT mapping: goupnp: error performing SOAP HTTP request: Post http://192.168.1.1:60000/446ce143/upnp/control/WANIPConn1: dial tcp 192.168.1.1:60000: i/o timeout
[2021-03-02 09:04:25]  INFO [consensus] Finalizing block block.Hash=0x84cd70f34788f4004e868edc0dab2ed4ee0dd01db7ff144eb753f6f2e1c31092 block.Height=9393805
[2021-03-02 09:04:25]  INFO [consensus] Notified finalized block, height=9393805
[2021-03-02 09:04:25]  INFO [rpc] Processing finalized block, height=9393805
[2021-03-02 09:04:25]  INFO [rpc] Done processing finalized block, height=9393805
[2021-03-02 09:04:26]  INFO [ledger] Commit to data store, height: 9393807, rootHash: 0x897bfcddaa7be2ae8e65f0ea52bd93bc96aa3a974f64ed12928f4811482d614c
[2021-03-02 09:04:26]  INFO [request] Sync progress current chain tip=0xcd4fcfb11532e44efabc251ad868b2442db704350cce47913a612364998df11a orphan blocks=0 pending block hashes=1214
[2021-03-02 09:04:28]  INFO [consensus] Finalizing block block.Hash=0xcd4fcfb11532e44efabc251ad868b2442db704350cce47913a612364998df11a block.Height=9393806
[2021-03-02 09:04:28]  INFO [consensus] Notified finalized block, height=9393806
[2021-03-02 09:04:28]  INFO [rpc] Processing finalized block, height=9393806
[2021-03-02 09:04:28]  INFO [rpc] Done processing finalized block, height=9393806
[2021-03-02 09:04:29]  INFO [ledger] Commit to data store, height: 9393808, rootHash: 0xbdfbbc3c19ff6c25903370b258eaee695bbef2a03426723659298c3f855d7a60
[2021-03-02 09:04:30]  INFO [request] Sync progress current chain tip=0xb32bf5d9f0c8afcdc89f52bb6b74c26c97370ed42fad4ec340ba2913209561ae orphan blocks=0 pending block hashes=1214
[2021-03-02 09:04:31]  INFO [ledger] Prune state from height 9391745 to 9391760
[2021-03-02 09:04:31]  INFO [ledger] Prune state, idx: 0, height: 9391760, StateHash: 0x78ea973b3fab39f6859a55adca69462b39cd64d67e816353781170530539d5e0
[2021-03-02 09:04:31]  INFO [store] Trie.Prune, t.originalRoot: 0x78ea973b3fab39f6859a55adca69462b39cd64d67e816353781170530539d5e0, t.root: {060c0703020f: <a87b740d99589d2bae5cefcf531fcef693350c7a03b1c4d88eefbd1dc2d62e68> }
[2021-03-02 09:04:31]  INFO [store] Trie.Prune done
[2021-03-02 09:04:31]  INFO [ledger] Prune state, idx: 0, height: 9391759, StateHash: 0x724a7606de478daf12319de2f3c46ae02467280f0bed171941d36a42b8a64b25
[2021-03-02 09:04:31]  INFO [store] Trie.Prune, t.originalRoot: 0x724a7606de478daf12319de2f3c46ae02467280f0bed171941d36a42b8a64b25, t.root: {060c0703020f: <6cfeba506335299bb22864c16b88fecf4bb2e64a2c3cb99c52e96d50facca13a> }
[2021-03-02 09:04:31]  INFO [store] Trie.Prune done
[2021-03-02 09:04:31]  INFO [ledger] Prune state, idx: 0, height: 9391758, StateHash: 0x4b4c9537c9efe66335977ab8b43597796dc3fdeb30c3f7b970d8670130618fc6
[2021-03-02 09:04:31]  INFO [store] Trie.Prune, t.originalRoot: 0x4b4c9537c9efe66335977ab8b43597796dc3fdeb30c3f7b970d8670130618fc6, t.root: {060c0703020f: <329903e1d63f917b650fb274d6de9b86936dbd491af3bc9a197f9a26be18e7a0> }
[2021-03-02 09:04:31]  INFO [store] Trie.Prune done
[2021-03-02 09:04:31]  INFO [ledger] Prune state, idx: 0, height: 9391757, StateHash: 0xe50000fc7d560a99f6b203f83149e645ddc070db9aac27979fa7728a95843e9d
[2021-03-02 09:04:31]  INFO [store] Trie.Prune, t.originalRoot: 0xe50000fc7d560a99f6b203f83149e645ddc070db9aac27979fa7728a95843e9d, t.root: {060c0703020f: <f31e5c41f15f72cc98ce81b59e62da07b614b960ceac739942a6758daff9ba0f> }
[2021-03-02 09:04:31]  INFO [store] Trie.Prune done
[2021-03-02 09:04:31]  INFO [ledger] Prune state, idx: 0, height: 9391756, StateHash: 0xe244f767b05052145d2a28ce803abe50e7c5463e01ccfa97017b865cea9134eb
[2021-03-02 09:04:31]  INFO [store] Trie.Prune, t.originalRoot: 0xe244f767b05052145d2a28ce803abe50e7c5463e01ccfa97017b865cea9134eb, t.root: {060c0703020f: <769dec3e60da048a00c4d96b3dc11d125747d809c13d52608515d28e0de3abd0> }
[2021-03-02 09:04:32]  INFO [store] Trie.Prune done
[2021-03-02 09:04:32]  INFO [ledger] Prune state, idx: 0, height: 9391755, StateHash: 0x734bc8eed43d78b0dec4641c174fa979005167f02867f3d9b91bc46e4ad4ca3d
[2021-03-02 09:04:32]  INFO [store] Trie.Prune, t.originalRoot: 0x734bc8eed43d78b0dec4641c174fa979005167f02867f3d9b91bc46e4ad4ca3d, t.root: {060c0703020f: <f46e58ed50d84e388996a752ef6dd2e40615f2095df566f7e037ae892decaf8d> }
[2021-03-02 09:04:32]  INFO [store] Trie.Prune done
[2021-03-02 09:04:32]  INFO [ledger] Prune state, idx: 0, height: 9391754, StateHash: 0x35ab005ca88881858171132ed9a73eda83dc4e9597b56b302ed8bf1873391911
[2021-03-02 09:04:32]  INFO [store] Trie.Prune, t.originalRoot: 0x35ab005ca88881858171132ed9a73eda83dc4e9597b56b302ed8bf1873391911, t.root: {060c0703020f: <d7daaf40f8444130b149827878580a84b62b8998a7e45176791b9dfb8ee8b8a6> }
[2021-03-02 09:04:32]  INFO [store] Trie.Prune done
[2021-03-02 09:04:32]  INFO [ledger] Prune state, idx: 0, height: 9391753, StateHash: 0x7d8afced1d6aac31e98f43a466ed1c74a8f7525be7235116f56f664d5c366add
[2021-03-02 09:04:32]  INFO [store] Trie.Prune, t.originalRoot: 0x7d8afced1d6aac31e98f43a466ed1c74a8f7525be7235116f56f664d5c366add, t.root: {060c0703020f: <5353ec89b22da14dee36c2a04f0368e4f35f9311cd407eb1b3adeb0843062a57> }
[2021-03-02 09:04:32]  INFO [store] Trie.Prune done
[2021-03-02 09:04:32]  INFO [ledger] Prune state, idx: 0, height: 9391752, StateHash: 0xc724fc1a422d23f27cdb5e9a6a0d717a9f40bbddc4625b9715eebf73fa83f142
[2021-03-02 09:04:32]  INFO [store] Trie.Prune, t.originalRoot: 0xc724fc1a422d23f27cdb5e9a6a0d717a9f40bbddc4625b9715eebf73fa83f142, t.root: {060c0703020f: <451f0295ad3148a57a1cf06fc6b6ad8250c23c3826f0294618fe89145a0a2a00> }
[2021-03-02 09:04:32]  INFO [store] Trie.Prune, t.originalRoot: 0x7898e80270b7091bc65eae1538bda93c413728a6ef6593c94410c73c75d235b4, t.root: [
  0: <f2fc0272604f6953644e12ab54c5c12e471f68c8e706bcaad488fee3d00bc54e> 1: <fc5607bdd0f8457de870ea7dd0eb1188ad1271793b2bab5a8263482ecc34291a> 2: <nil> 3: <nil> 4: <nil> 5: <76e84c36043c7b12a02800ab5712c229d6576028e436f108205c1b6489f16128> 6: <nil> 7: <nil> 8: <347be60977084aae7ac105fbab610050434144f7abb0ccc67ad89ab4184cecc4> 9: <85109d5008a7e8e7187707b3fbafd8b09aad1f634392e5d54f7da7eb032631b4> a: <bcfc8a56a4d298db075da0e1c0de3095f537e39ee96f8b9c92fc45464e4a333c> b: <nil> c: <a4eb9208a5c12ae5b6e7015ab9fe33510665b2fafb61248a8e24c2ff31a1f4b6> d: <nil> e: <nil> f: <86b4cfb439e2e222d802a98f5f7ed90b697c1f62b8ea553f4d6936b36389b27a> [17]: <nil>
]
[2021-03-02 09:04:32]  INFO [store] Trie.Prune done
[2021-03-02 09:04:32]  INFO [store] Trie.Prune, t.originalRoot: 0x04530893a915235b359d16e796c0b9b489b6986e9a7c8789b7c408fe970935cd, t.root: [
  0: <a2a8285334a2214704ef312179191087754cab15180a2e8954ae1f655819ed1d> 1: <nil> 2: <nil> 3: <nil> 4: <nil> 5: <nil> 6: <e4ad3de65385259f3562c0229a78a8f849576cf4cd42015e22139ed613538a50> 7: <3875db0bf50477c55aa6d58ab41df4fbf0691d8a5b2565173bc5238950384a91> 8: <nil> 9: <nil> a: <e70cbde31d64d23852760433948d645aeba83b62bbacbdfe072789adbe20b7bc> b: <421a572b7a567067992154d36a91a5722606fbc60e6edfc2ba4983bf8f253b1e> c: <nil> d: <nil> e: <nil> f: <nil> [17]: <nil>
]
[2021-03-02 09:04:32]  INFO [store] Trie.Prune done
[2021-03-02 09:04:33]  INFO [store] Trie.Prune, t.originalRoot: 0x788b1ba3d36b21861a59a2761d2d2b86950414182dd8b04dbcd382e68a9eb789, t.root: [
  0: <237e98d364217db461b850e05a3cd168b5c650b8b7d4538b1f83a9696f4cc837> 1: <ca45b0eab3e5e8b734e035bfb8b5bb6cb93263406201da29e74b127e01dbffa6> 2: <e9c72e176db3e96616cf14024bc5bd872da3711fc8a11e41b367e9018ae18bed> 3: <c2cd2589eb7f58474921ec98392ae7a925b26023c2dca52fea0cbc81d0a55be1> 4: <72c747973e5f85c16a3186913933e1bf2adefc894252b1fc2748f470ebf70a7f> 5: <fe8e9d5860b1d425cf7c563fa54bbc19282e7e7847f8667bd906650a13616fe5> 6: <bab240a913509fe2a7b483a3ca1a82044f18b9294c2e5d19d42fc1349ee1e7c3> 7: <bd9a894b0e580ecc02005ccda6000d509084d38c96ec72756e843c403346b879> 8: <7780109f0737346e350a3e09f07042834f86e78c3b9a6324c487c4941609c79d> 9: <dc5cda535b271d89d6489c5ada18edd07ca2cc167b91780ed33b84e6eec10f87> a: <b3e1ddf159eee5a72f6bc655809d52adbaa8d0604465717f1a73a8e2323e6121> b: <306653866cfab1616eec66e02a697cb97ce1cf09a86f8d45da1f6917596f108e> c: <b2980125f85768766a16d413a5884e0ec256d1680216d2739111d17a67505e7f> d: <097ac8d3dc509448fb0c6030b79ba60cd1452296b1f38e98e8b1864a39c824b1> e: <fee555e15da86be9f84e10bd51e6aaf5d61c7a2683b650c8097f119eb549f10d> f: <e91ae62d44e9de210a0e35e4152d8b91da1799f9e8a4923c35f864a0868d2cf3> [17]: <nil>
]
[2021-03-02 09:04:33]  INFO [store] Trie.Prune done
[2021-03-02 09:04:33]  INFO [store] Trie.Prune done
[2021-03-02 09:04:33]  INFO [ledger] Prune state, idx: 0, height: 9391751, StateHash: 0xf8d7483b468957bf129d83168a2fd7ae7aa2a15407344a7ce80042f223413e38
[2021-03-02 09:04:33]  INFO [store] Trie.Prune, t.originalRoot: 0xf8d7483b468957bf129d83168a2fd7ae7aa2a15407344a7ce80042f223413e38, t.root: {060c0703020f: <a6a48b25bd8a00d8e7b259078005201f029d618f771066bd376b4f9c1b7a1e49> }
[2021-03-02 09:04:33]  INFO [store] Trie.Prune done
[2021-03-02 09:04:33]  INFO [ledger] Prune state, idx: 0, height: 9391750, StateHash: 0x8d6da90227997e8a12f17b34f5cd28c116ee576dd855c80b74d5fcf50d3b9079
[2021-03-02 09:04:33]  INFO [store] Trie.Prune, t.originalRoot: 0x8d6da90227997e8a12f17b34f5cd28c116ee576dd855c80b74d5fcf50d3b9079, t.root: {060c0703020f: <dec9aaf86b8b5c7d885a731dc988ad210b0c1e149c39071710e5ff26d2756d3c> }
[2021-03-02 09:04:33]  INFO [store] Trie.Prune done
[2021-03-02 09:04:33]  INFO [ledger] Prune state, idx: 0, height: 9391749, StateHash: 0x1212dc3f54fea487301172d83430b32bf6d20b6d1a1f3c009582b719c1e46111
[2021-03-02 09:04:33]  INFO [store] Trie.Prune, t.originalRoot: 0x1212dc3f54fea487301172d83430b32bf6d20b6d1a1f3c009582b719c1e46111, t.root: {060c0703020f: <4b5a81c400b6fce741ad7b3526c1596a4be4dd6110d8a64368c30284f4f8349e> }
[2021-03-02 09:04:33]  INFO [store] Trie.Prune done
[2021-03-02 09:04:33]  INFO [ledger] Prune state, idx: 0, height: 9391748, StateHash: 0x5c5b64cf3d971868fc9a0c9678eb581b40daece64fbae7f8c594bbd7ed4697bc
[2021-03-02 09:04:33]  INFO [store] Trie.Prune, t.originalRoot: 0x5c5b64cf3d971868fc9a0c9678eb581b40daece64fbae7f8c594bbd7ed4697bc, t.root: {060c0703020f: <546e7dd6960ac3c6667ed71f6802c3e98dc21c14853aa2ad7f0549db474c7447> }
[2021-03-02 09:04:33]  INFO [store] Trie.Prune done
[2021-03-02 09:04:33]  INFO [ledger] Prune state, idx: 0, height: 9391747, StateHash: 0xaa3034f11c94724572a57c84c832afb7f5044eeb77f856670d6a9cbce8a3b499
[2021-03-02 09:04:33]  INFO [store] Trie.Prune, t.originalRoot: 0xaa3034f11c94724572a57c84c832afb7f5044eeb77f856670d6a9cbce8a3b499, t.root: {060c0703020f: <31f24fe518b9fc7f9c09509050695e51030274c273b018a785145d6e79c470a1> }
[2021-03-02 09:04:33]  INFO [store] Trie.Prune done
[2021-03-02 09:04:33]  INFO [ledger] Prune state, idx: 0, height: 9391746, StateHash: 0xe74094d7231e65f74089fdd6f5eb64a96c8bb5a5b4cdf77e716c972ed5387082
[2021-03-02 09:04:33]  INFO [store] Trie.Prune, t.originalRoot: 0xe74094d7231e65f74089fdd6f5eb64a96c8bb5a5b4cdf77e716c972ed5387082, t.root: {060c0703020f: <152f2e06d818f04d5dacc3ee6be40bef6053a88abcf6779367b89a29581c187b> }
[2021-03-02 09:04:34]  INFO [store] Trie.Prune done
[2021-03-02 09:04:34]  INFO [ledger] Prune state, idx: 0, height: 9391745, StateHash: 0x2abfd89fb2df74b5a706382490aa9ba5461292156b8f2b9763d4c369355a8783
[2021-03-02 09:04:34]  INFO [store] Trie.Prune, t.originalRoot: 0x2abfd89fb2df74b5a706382490aa9ba5461292156b8f2b9763d4c369355a8783, t.root: {060c0703020f: <3eb21844173236c3fbee57ee61a71bed02671b6a196523282904ad202d44cf99> }
[2021-03-02 09:04:34]  INFO [request] Sync progress current chain tip=0xb32bf5d9f0c8afcdc89f52bb6b74c26c97370ed42fad4ec340ba2913209561ae orphan blocks=0 pending block hashes=1214
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x908836]

goroutine 117 [running]:
github.com/thetatoken/theta/store/trie.(*Trie).pruneNode(0xc046110870, 0x0, 0x0, 0xc008012388, 0x1888d82ee43a3522, 0x0)
        /home/ubuntu/go/src/github.com/thetatoken/theta/store/trie/trie.go:523 +0x26
github.com/thetatoken/theta/store/trie.(*Trie).pruneChildren(0xc046110870, 0x16c9c60, 0xc0214503c0, 0xc008012388, 0x1, 0x0)
        /home/ubuntu/go/src/github.com/thetatoken/theta/store/trie/trie.go:590 +0x24b
github.com/thetatoken/theta/store/trie.(*Trie).pruneNode(0xc046110870, 0x16c9c60, 0xc0214503c0, 0xc008012388, 0x483c45068f4c4565, 0x0)
        /home/ubuntu/go/src/github.com/thetatoken/theta/store/trie/trie.go:540 +0x13b
github.com/thetatoken/theta/store/trie.(*Trie).pruneChildren(0xc046110870, 0x16c9c60, 0xc0208c0000, 0xc008012388, 0x1, 0x0)
        /home/ubuntu/go/src/github.com/thetatoken/theta/store/trie/trie.go:590 +0x24b
github.com/thetatoken/theta/store/trie.(*Trie).pruneNode(0xc046110870, 0x16c9c60, 0xc0208c0000, 0xc008012388, 0x9c11bef8f65899c, 0x0)
        /home/ubuntu/go/src/github.com/thetatoken/theta/store/trie/trie.go:540 +0x13b
github.com/thetatoken/theta/store/trie.(*Trie).pruneChildren(0xc046110870, 0x16c9ce0, 0xc046110a00, 0xc008012388, 0x1, 0x0)
        /home/ubuntu/go/src/github.com/thetatoken/theta/store/trie/trie.go:564 +0x6ff
github.com/thetatoken/theta/store/trie.(*Trie).pruneNode(0xc046110870, 0x16c9ce0, 0xc046110a00, 0xc008012388, 0x9d5a72492d1d9a38, 0x0)
        /home/ubuntu/go/src/github.com/thetatoken/theta/store/trie/trie.go:540 +0x13b
github.com/thetatoken/theta/store/trie.(*Trie).pruneChildren(0xc046110870, 0x16c9c60, 0xc02075be00, 0xc008012388, 0x1, 0x0)
        /home/ubuntu/go/src/github.com/thetatoken/theta/store/trie/trie.go:590 +0x24b
github.com/thetatoken/theta/store/trie.(*Trie).pruneNode(0xc046110870, 0x16c9c60, 0xc02075be00, 0xc008012388, 0x99f7641d9622b7bb, 0x0)
        /home/ubuntu/go/src/github.com/thetatoken/theta/store/trie/trie.go:540 +0x13b
github.com/thetatoken/theta/store/trie.(*Trie).pruneChildren(0xc046110870, 0x16c9c60, 0xc02075bcc0, 0xc008012388, 0x1, 0x0)
        /home/ubuntu/go/src/github.com/thetatoken/theta/store/trie/trie.go:590 +0x24b
github.com/thetatoken/theta/store/trie.(*Trie).pruneNode(0xc046110870, 0x16c9c60, 0xc02075bcc0, 0xc008012388, 0x99cf442d20ad0429, 0x0)
        /home/ubuntu/go/src/github.com/thetatoken/theta/store/trie/trie.go:540 +0x13b
github.com/thetatoken/theta/store/trie.(*Trie).pruneChildren(0xc046110870, 0x16c9ce0, 0xc0461108c0, 0xc008012388, 0x1, 0x0)
        /home/ubuntu/go/src/github.com/thetatoken/theta/store/trie/trie.go:564 +0x6ff
github.com/thetatoken/theta/store/trie.(*Trie).pruneNode(0xc046110870, 0x16c9ce0, 0xc0461108c0, 0xc008012388, 0xc008012310, 0x2)
        /home/ubuntu/go/src/github.com/thetatoken/theta/store/trie/trie.go:540 +0x13b
github.com/thetatoken/theta/store/trie.(*Trie).Prune(0xc046110870, 0xc008012388, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/thetatoken/theta/store/trie/trie.go:510 +0x1be
github.com/thetatoken/theta/store/treestore.(*TreeStore).Prune(...)
        /home/ubuntu/go/src/github.com/thetatoken/theta/store/treestore/treestore.go:116
github.com/thetatoken/theta/ledger/state.(*StoreView).Prune(0xc046110960, 0xb574dfb29fd8bf2a, 0xa59baa90243806a7)
        /home/ubuntu/go/src/github.com/thetatoken/theta/ledger/state/storeview.go:642 +0x59
github.com/thetatoken/theta/ledger.(*Ledger).pruneStateForRange(0xc0000b1560, 0x8f4e81, 0x8f4e90, 0x6, 0x10f5e00)
        /home/ubuntu/go/src/github.com/thetatoken/theta/ledger/ledger.go:492 +0xac0
github.com/thetatoken/theta/ledger.(*Ledger).PruneState(0xc0000b1560, 0x8f4e90, 0x22, 0x800)
        /home/ubuntu/go/src/github.com/thetatoken/theta/ledger/ledger.go:418 +0x265
github.com/thetatoken/theta/consensus.(*ConsensusEngine).pruneState(0xc01e2800b0, 0x8f5690)
        /home/ubuntu/go/src/github.com/thetatoken/theta/consensus/engine.go:1163 +0xf9
github.com/thetatoken/theta/consensus.(*ConsensusEngine).handleNormalBlock(0xc01e2800b0, 0xc070e98330)
        /home/ubuntu/go/src/github.com/thetatoken/theta/consensus/engine.go:644 +0xb36
github.com/thetatoken/theta/consensus.(*ConsensusEngine).handleBlock(0xc01e2800b0, 0xc012ada580)
        /home/ubuntu/go/src/github.com/thetatoken/theta/consensus/engine.go:529 +0x152
github.com/thetatoken/theta/consensus.(*ConsensusEngine).processMessage(0xc01e2800b0, 0x1256500, 0xc012ada580, 0x1)
        /home/ubuntu/go/src/github.com/thetatoken/theta/consensus/engine.go:319 +0x537
github.com/thetatoken/theta/consensus.(*ConsensusEngine).mainLoop(0xc01e2800b0)
        /home/ubuntu/go/src/github.com/thetatoken/theta/consensus/engine.go:259 +0x549
created by github.com/thetatoken/theta/consensus.(*ConsensusEngine).Start
        /home/ubuntu/go/src/github.com/thetatoken/theta/consensus/engine.go:150 +0x1af
mike@beta-1:~/theta_mainnet/bin$

**Comment by AquaWookie** [comment]
Getting the same error as of about 2 days ago:

![image](https://user-images.githubusercontent.com/37837732/118205943-8dc6a300-b42f-11eb-94a8-25bb5618a40e.png)

**Comment by the-quantum-rabbit** [comment]
I managed to get round my issue by deleting the db and reloading a new snapshot before restarting the node.  I had to load a new snapshot more than once!!!  which seems counter intuitive.
